### PR TITLE
Remove use of "[]" to access data

### LINKED ISSUE #55: Convert all the `[ ]` access to `get()`.
The `[]` might crash when out of index, but as a library, we should never crashes.

Please change it to `get()` and handle the errors.

### PR DESCRIPTION
**Pull request by ffmancera**
This a good first step on error handling, in a following PR we should raise the error or panic instead of ignore the values.

### CODE REVIEW

**Review by tyll — COMMENTED** [review]
FYI: The commit message does not follow best practices that are documented for Nmstate: https://github.com/nmstate/nmstate/blob/base/CONTRIBUTING.md#write-a-good-commit-message

Especially it is not documenting the "why: ` Explain the problem that this commit is solving. Focus on why you are making 
 this change as opposed to how (the code explains that)."

**Comment by ffmancera** [comment]
> FYI: The commit message does not follow best practices that are documented for Nmstate: https://github.com/nmstate/nmstate/blob/base/CONTRIBUTING.md#write-a-good-commit-message
> 
> Especially it is not documenting the "why: ` Explain the problem that this commit is solving. Focus on why you are making
> this change as opposed to how (the code explains that)."

Thank you @tyll! Yes, I will reword the commit title and messages. Thank you 👍

**Review by cathay4t — CHANGES_REQUESTED** [review]
This PR is not improving but make the code worse when debugging problems.

Instead, I would like to see we change functions return `Result<> `and  `?` for converting
it to `NisporError`.

Meanwhile, please don't use `.ok()` which hide the error message.

**Comment by ffmancera** [comment]
> This PR is not improving but make the code worse when debugging problems.
> 
> Instead, I would like to see we change functions return `Result<> `and `?` for converting
> it to `NisporError`.
> 
> Meanwhile, please don't use `.ok()` which hide the error message.

In that case, I will modify all the functions to return Result<>. Thanks.

**Comment by ffmancera** [comment]
> This PR is not improving but make the code worse when debugging problems.
> 
> Instead, I would like to see we change functions return `Result<> `and `?` for converting
> it to `NisporError`.
> 
> Meanwhile, please don't use `.ok()` which hide the error message.

Done :-)

File: src/lib/ifaces/iface.rs [hunk 1]
```diff
@@ -279,9 +284,11 @@ pub(crate) fn parse_nl_msg_to_iface(nl_msg: &LinkMessage) -> Option<Iface> {
             for info in infos {
                 if let nlas::Info::SlaveKind(d) = info {
                     // Remove the tailing \0
-                    match std::str::from_utf8(&(d.as_slice()[0..(d.len() - 1)]))
+                    match std::ffi::CStr::from_bytes_with_nul(&d.as_slice())
+                        .ok()
```
Comment (cathay4t) [inline src/lib/ifaces/iface.rs]: Please replace the use of `.ok().and_then()` to `?`

File: src/lib/error.rs [hunk 2]
```diff
@@ -57,3 +57,12 @@ impl std::convert::From<std::io::Error> for NisporError {
         }
     }
 }
+
+impl std::convert::From<&str> for NisporError {
```
Comment (cathay4t) [inline src/lib/error.rs]: Converting `&str` to `NisporError` seems too dangerous to me, normally we only convert other type of errors into NisporError.

You may try to implement the `NisporError::bug(msg: &str)` to simply the effort on create a `NisporError` with `ErrorKind::NisporBug`

**Review by cathay4t — CHANGES_REQUESTED** [review]

File: src/lib/ifaces/iface.rs (hunk 1 above)
Comment (ffmancera) [reply src/lib/ifaces/iface.rs]: Done, thank you!

File: src/lib/error.rs (hunk 2 above)
Comment (ffmancera) [reply src/lib/error.rs]: Done! I've implemented the bug() function for NisporError. Thanks!

File: src/lib/error.rs [hunk 3]
```diff
@@ -40,6 +49,24 @@ impl std::convert::From<rtnetlink::Error> for NisporError {
     }
 }
 
+impl std::convert::From<std::ffi::FromBytesWithNulError> for NisporError {
+    fn from(e: std::ffi::FromBytesWithNulError) -> Self {
+        NisporError {
+            kind: ErrorKind::NisporBug,
+            msg: e.to_string(),
```
Comment (cathay4t) [inline src/lib/error.rs]: How about `format!("FromBytesWithNulError: {}", e)` so that we could know the source this error.

File: src/lib/error.rs [hunk 4]
```diff
@@ -40,6 +49,24 @@ impl std::convert::From<rtnetlink::Error> for NisporError {
...
+        }
+    }
+}
+
+impl std::convert::From<std::str::Utf8Error> for NisporError {
+    fn from(e: std::str::Utf8Error) -> Self {
+        NisporError {
+            kind: ErrorKind::NisporBug,
+            msg: e.to_string(),
```
Comment (cathay4t) [inline src/lib/error.rs]: How about `format!("Utf8Error: {}", e)` so that we could know the source this error.

**Review by cathay4t — CHANGES_REQUESTED** [review]

File: src/lib/error.rs (hunk 3 above)
Comment (ffmancera) [reply src/lib/error.rs]: Done! Thanks!

File: src/lib/error.rs (hunk 4 above)
Comment (ffmancera) [reply src/lib/error.rs]: Done, thanks!

**Review by cathay4t — APPROVED** [review]
